### PR TITLE
implement hideButtons setting

### PR DESCRIPTION
**Pull request by jessev14**
if setting is enabled, buttons are hidden during renderChatMessage hook.
new context menus are added to chat messages that emit a socket event (for everyone via socketlib) to toggle the button visibility.
also adds english localization file.

### CODE REVIEW

**Comment by jessev14** [comment]
feel free to reject if you think this is too finicky/out of scope. I mostly made it for myself and figured I'd give you the option to look at it.

**Comment by akrigline** [comment]
Sorry, what's the use case here? I guess for people who want the functionality but don't like the button being always visible?

This would allow the GM to enable the buttons for a given message instead of all?

**Comment by jessev14** [comment]
yeah that's pretty much the use case.
players can show the buttons too, as long as they're the author of the message

**Comment by akrigline** [comment]
Gonna close this to keep this package simple and config-free. No config is just so much more maintenance friendly for my ever-dwindling time to devote to these things.

**Pull request closed without merging**
